import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { TailwindIndicator } from '@/components/TailwindIndicator'
import { cn } from '@/lib/utilities'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn('min-h-screen', inter.className)}>
        <Provider>{children}</Provider>
        <TailwindIndicator />
      </body>
    </html>
  )
}
